const MONTH_LOOKUP = {
    0: 'Jan',
    1: 'Feb',
    2: 'Mar',
    3: 'Apr',
    4: 'May',
    5: 'Jun',
    6: 'Jul',
    7: 'Aug',
    8: 'Sep',
    9: 'Oct',
    10: 'Nov',
    11: 'Dec',
};

// Used in autogenerated JUCE files
// eg. 15 Mar 2021 9:14:21pm
export const getDateString = (): string => {
    const now = new Date();
    const day = now.getUTCDate();
    const month = MONTH_LOOKUP[now.getUTCMonth()];
    const year = now.getUTCFullYear();
    const fullhour = now.getUTCHours();
    const minutes = now.getUTCMinutes();
    const seconds = now.getUTCSeconds();

    let hour;
    if (fullhour >= 13) {
        hour = fullhour - 12;
    } else if (fullhour === 0) {
        hour = 12;
    }

    const meridiem = fullhour < 12 ? 'am' : 'pm';
    return `${day} ${month} ${year} ${hour}:${minutes}:${seconds}${meridiem}`;
};

export const cleanString = (str: string): string => {
    // remove spaces and non alphanumeric characters from names
    let s = str.replace(/\s/g, '').replace(/[^a-zA-Z0-9]/g, '_');
    // prepends a _ if the name begins with a number
    if (/^[0-9]/.test(s)) {
        s = '_' + s;
    }
    return s;
};
